### PR TITLE
Ability to set context in middleware & capture responses

### LINKED ISSUE #12: Ability to set context in middleware & capture responses
Ability to inherit context in middleware

Right now, command middleware is pretty limited because:

1. It can not capture the responses in any way. Traditionally, in an http middleware I could do something like this:

```go
	return func(handler slacker.CommandHandler) slacker.CommandHandler {
		return func(cmdCtx *slacker.CommandContext) {
                      ctx := context.WithValue(cmdCtx.Context(), "test", "value")
                     // in gin this would be c.Request.WithContext (or c.WithContext in net/http
                      cmdCtx.WithContext(ctx)
                      next()
                     // within the next method I could query this context
		}
	}

```

There's nothing like that at all. For an example use case, you could do thing s like otel with this. I've put together an example here w/o the [context pass down](https://github.com/synapsecns/sanguine/blob/df89133f4ca42df11465cb3334f1cf6ff1706ce3/contrib/opbot/botmd/middleware.go#L13-L24)

It would also be very standard to be able to capture the response after next() is called.

This could either be done by overwriting the writer, or with a hook on reply

### PR DESCRIPTION
**Pull request by Gobd**
Fixes #12

Done in the same way as http.Request WithContext https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/net/http/request.go;l=353

### CODE REVIEW

**Comment by raed-shomali** [comment]
Thank you!

**Comment by trajan0x** [comment]
Sorry, maybe I'm missing something here. Does this address response capture?

**Comment by Gobd** [comment]
This should allow you to do
```
ctx := context.WithValue(cmdCtx.Context(), "test", "value")
cmdCtx = cmdCtx.WithContext(ctx)
```

to store any value you want in the context then access it in the next handler.

**Comment by raed-shomali** [comment]
Might be nice to create an example of this for future users in the examples folder

**Pull request merged**
