### PR TITLE
feat: PLMSE-2085 changes to allow unit testing

### PR DESCRIPTION
**Pull request by icahoon-cbsi**
- adds `NewCommandContext` which allows unit tests to create a CommandContext independent of the rest of the module

- adds go fmt changes for the examples directory

- comments out existing github actions
- adds build github action
- adds a simple Makefile

### CODE REVIEW

**Comment by raed-shomali** [comment]
Thank you very much for this!

Any reason to keep the commented out code?

I want to make sure @arusso gets the chance to review this too since he wrote these GitHub actions

**Comment by arusso** [comment]
I'm guessing this was intended for a fork and not this repo based on the internal-looking issue id.

**Comment by icahoon-cbsi** [comment]
My bad, sorry about that.

**Comment by raed-shomali** [comment]
You don't need to apologize!

If there are code changes that would improve the test-ability of the framework for other users too, we would welcome them!

**Pull request closed without merging**
