### PR TITLE
chore: Update slack dep to v0.13

### LINKED ISSUE #8: Bot fails to start when using github.com/slack-go/slack v0.13.0
When go: upgraded github.com/slack-go/slack v0.12.2 => v0.13.0 bot fails to start with the following error:

`# github.com/slack-io/slacker
../../go/pkg/mod/github.com/slack-io/slacker@v0.1.0/slacker.go:547:40: cannot use messageEvent.BotID (variable of type string) as slack.GetBotInfoParameters value in argument to s.slackClient.GetBotInfo`

### PR DESCRIPTION
**Pull request by llinros**
fixes #8

### CODE REVIEW

**Comment by sheldonhull** [comment]
@raed-shomali  this broke my current upgrade, so would be great to get in if possible.

**Comment by raed-shomali** [comment]
Thank you for this!

**Comment by sheldonhull** [comment]
can you cut a release for this? If you don't have the release automation setup to post the release notes and create the tag I'd be glad to contribute it.

**Comment by arusso** [comment]
Once a version is tagged and pushed it should generate release and changelog

**Comment by raed-shomali** [comment]
v0.1.1 has been released

**Pull request merged**
